---
#This role remediates observed open Apache 2.4 SiteUnix STIG vulnerabilities on RHEL8.

- name: stigrule_214277_install_mod_session
  ansible.builtin.yum:
    name: "mod_session"
    state: latest
  tags:
      - V-214277

- name: stigrule_214277_add_lines_to_httpd_conf
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: 'LoadModule usertrack_module modules/mod_usertrack.so'
    insertbefore: 'Include conf.modules.d/*.conf'
    state: present
  tags:
    - V-214277

...
