---
#This role remediates observed open Apache 2.4 SiteUnix STIG vulnerabilities on RHEL8.

- name: stigrule_214277_install_mod_session
  ansible.builtin.yum:
    name: "mod_session"
    state: latest
  tags:
      - V-214277

- name: stigrule_214278_Modify_SSLProtocal_add+TLSv1.2
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: ^#SSLProtocol
    line: 'SSLProtocol all +TLSv1.2'
  tags:
    - V-214278

...
